version: '3'
services:
  maven:
    build: .
    volumes:
      - ${BUILD_TARGET}/${PROJECT}:/usr/src/content
      - ~/.m2:/root/.m2
    working_dir: /usr/src/content
    command: >
      bash -c "rm -rf source
      && git clone $REPO source
      && cd source
      && mvn clean install
      && cd ..
      && find source/target -name '*.jar' -exec cp {} . \;
      && rm -rf source"
